name: "Docker build and push"
on: push

jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
        - name: docker build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker Login
          run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}
          
        - name: Docker publish  
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME$IMAGE_NAME:latest