name: My First Workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: listing files and modify
        run: |
          echo "all my messages"
          ls -al
          cat README.md
        
      - name: geneate ASCII
        run: cowsay -f dragaon "run over...i am the dragon" >> dragon.txt
       