name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: welcome
          run: echo "welcome to github"
          
       # - name: thanks for starting
       #   run: echo" started my learning"
          
       # - name: more to go
       #   run: echo "chooskundhm inka"  