name: "My first workflow"
on: workflow_dispatch

jobs:
    my_first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: list the files
          run: ls -la
          
        - name: read readme file
          run: cat README.md  