name: Generate ascill

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Download and install cowsay
        run: sudo apt-get install cowsay -y

      - name: execu cowsay
        run: cowsay -f dragon "Hey am dragon" >> dragon.txt

      - name: uploading dragon file
        uses: actions/upload-artifact@v4
        with:
          name: my-dragon-file
          path: dragon.txt
        
        
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: download dragon file
        uses: actions/download-artifact@v4
        with:
          name: my-dragon-file
          

      - name: Checking the file exists
        run: grep -i "dragon" dragon.txt
        
  third_job: 
    needs: second_job
    runs-on: ubuntu-latest
    steps:
      - name: download dragon file
        uses: actions/download-artifact@v4
        with:
          name: my-dragon-file

      - name: viewing the file
        run: cat dragon.txt      
        

      