name: Generate ascill

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
    
      - name: Download and install cowsay
        run: sudo apt-get install cowsay -y

      - name: execu cowsay
        run: cowsay -f dragon "Hey am dragon" >> dragon.txt
        
        
  second_job:
    needs: first_job
    runs-on: ubunutu-latest
    steps:
      - name: Checking the file exists
        run: grep -i "dragon" dragon.txt
        
  third_job: 
    needs: [first_job, second_job]
    runs-on: ubuntu-latest
    steps:
      - name: viewing the file
        run: cat dragon.txt      
        

      