name: Generate ascill

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: list files
        run: |
          cd .github/workflows
          chmod +x script1.sh
          ./script1.sh
      

      