name: Generate ascill

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: list files
        run: |
          cd .git
          ls -latr
          cat  scrip1.sh
      

      