name: Generate ascill

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
    
      - name: list files
        run: ls -latr 
      

      