name: Generate ascill

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: listing files and modify
        run: |
          echo "all my messages"
          ls -al
          cat README.md

      - name: Executing shell script
        run: ./script1.sh

      - name: viewing dragon file
        run: cat dragon.txt  
    