name: Variables

on: push

jobs:
    Docker:
      runs-on: ubuntu-latest
      steps:
      - name: docker build
        env: 
          CONTAINER_REG: docker.io
          CONTAINER_USER: nkposa
          IMAGE_NAME: HimaB@96.
        run: echo build -t $CONTAINER_REG/$CONTAINER_USER/$IMAGE_NAME

    Docker_login:
      runs-on: ubuntu-latest
      steps:
        - name: docker log
          env:
            DOCKER_USERNAME: nkposa
            DOCKER_PW: HimaB@96.
          run: echo docker login using --username $DOCKER_USERNAME --pw $DOCKER_PW


          
             
              